replicaCount: 1

image:
  repository: bhatta007/myapp
  tag: b99cfa1ac0bcceaaa5a2509e2bc69def7b2b4543

containerPort: 4000


ingress:
  host: app.test

prometheus:
  host: prometheus.test 

service:
  name: nodejs-rest-api-service
  port: 4000


resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"