name: Docker Build and Push with Trivy Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

    # - name: Run Trivy vulnerability scan
    #   uses: aquasecurity/trivy-action@0.28.0
    #   with:
    #     image: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
    #     format: 'sarif'
    #     output: trivy-results.sarif
    #     exit-code: '0'

    # - name: Upload Trivy scan results
    #   uses: actions/upload-artifact@v4
    #   with:
    #     sarif_file: trivy-results.sarif

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
