# .github/workflows/deploy.yaml

name: Helm Deploy to Minikube

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # or choose a protected branch if needed

jobs:
  helm-deploy:
    runs-on: self-hosted  # This must be the machine where Minikube is running

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Uninstall previous Helm release (if exists)
        run: |
          try {
           helm status myapp --namespace default 2>$null
           $releaseExists = $LASTEXITCODE -eq 0
           } catch {
           $releaseExists = $false
          }

          if ($releaseExists) {
          Write-Host "Release 'myapp' found, uninstalling..."
           helm uninstall myapp --namespace default
           } else {
          Write-Host "No existing release 'myapp' to uninstall"
          }
          exit 0

      - name: Deploy to Minikube using Helm
        run: |
         helm upgrade --install myapp ./mychart --set image.repository=docker.io/${{ secrets.DOCKER_USERNAME }}/myapp --set image.tag=${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/myapp
          kubectl get pods -o wide

      - name: Clean up workspace
        run: |
          Remove-Item "$env:GITHUB_WORKSPACE\*" -Recurse -Force